# Multiple linear regression
### Can we predict the calorie content of a cereal?

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("cereals.csv")

In [7]:
y = df.calories.values
X = df[['sugars', 'carbo', 'protein', 'fat', 'sodium', 'fiber', 'potass']].values

In [22]:
X

array([[  6. ,   5. ,   4. ,   1. , 130. ,  10. , 280. ],
       [  8. ,   8. ,   3. ,   5. ,  15. ,   2. , 135. ],
       [  5. ,   7. ,   4. ,   1. , 260. ,   9. , 320. ],
       [  0. ,   8. ,   4. ,   0. , 140. ,  14. , 330. ],
       [  8. ,  14. ,   2. ,   2. , 200. ,   1. ,  -1. ],
       [ 10. ,  10.5,   2. ,   2. , 180. ,   1.5,  70. ],
       [ 14. ,  11. ,   2. ,   0. , 125. ,   1. ,  30. ],
       [  8. ,  18. ,   3. ,   2. , 210. ,   2. , 100. ],
       [  6. ,  15. ,   2. ,   1. , 200. ,   4. , 125. ],
       [  5. ,  13. ,   3. ,   0. , 210. ,   5. , 190. ],
       [ 12. ,  12. ,   1. ,   2. , 220. ,   0. ,  35. ],
       [  1. ,  17. ,   6. ,   2. , 290. ,   2. , 105. ],
       [  9. ,  13. ,   1. ,   3. , 210. ,   0. ,  45. ],
       [  7. ,  13. ,   3. ,   2. , 140. ,   2. , 105. ],
       [ 13. ,  12. ,   1. ,   1. , 180. ,   0. ,  55. ],
       [  3. ,  22. ,   2. ,   0. , 280. ,   0. ,  25. ],
       [  2. ,  21. ,   2. ,   0. , 290. ,   1. ,  35. ],
       [ 12. ,  13. ,   1. ,   0. ,  90. ,   1. ,  20. ],
       [ 13. ,  12. ,   1. ,   1. , 180. ,   0. ,  65. ],
       [  7. ,  10. ,   3. ,   3. , 140. ,   4. , 160. ],
       [  0. ,  21. ,   3. ,   0. ,  80. ,   1. ,  -1. ],
       [  3. ,  21. ,   2. ,   0. , 220. ,   1. ,  30. ],
       [ 10. ,  11. ,   2. ,   1. , 140. ,   2. , 120. ],
       [  5. ,  18. ,   2. ,   0. , 190. ,   1. ,  80. ],
       [ 13. ,  11. ,   2. ,   1. , 125. ,   1. ,  30. ],
       [ 11. ,  14. ,   1. ,   0. , 200. ,   1. ,  25. ],
       [  7. ,  14. ,   3. ,   0. ,   0. ,   3. , 100. ],
       [ 10. ,  12. ,   3. ,   2. , 160. ,   5. , 200. ],
       [ 12. ,  14. ,   3. ,   0. , 240. ,   5. , 190. ],
       [ 12. ,  13. ,   1. ,   1. , 135. ,   0. ,  25. ],
       [ 15. ,  11. ,   2. ,   0. ,  45. ,   0. ,  40. ],
       [  9. ,  15. ,   1. ,   1. , 280. ,   0. ,  45. ],
       [  5. ,  15. ,   3. ,   1. , 140. ,   3. ,  85. ],
       [  3. ,  17. ,   3. ,   0. , 170. ,   3. ,  90. ],
       [  4. ,  13. ,   3. ,   3. ,  75. ,   3. , 100. ],
       [ 11. ,  12. ,   1. ,   2. , 220. ,   1. ,  45. ],
       [ 10. ,  11.5,   3. ,   1. , 250. ,   1.5,  90. ],
       [ 11. ,  14. ,   1. ,   0. , 180. ,   0. ,  35. ],
       [  6. ,  17. ,   2. ,   1. , 170. ,   1. ,  60. ],
       [  9. ,  20. ,   3. ,   1. , 170. ,   2. ,  95. ],
       [  3. ,  21. ,   2. ,   1. , 260. ,   0. ,  40. ],
       [  6. ,  12. ,   4. ,   2. , 150. ,   2. ,  95. ],
       [ 12. ,  12. ,   2. ,   1. , 180. ,   0. ,  55. ],
       [  3. ,  16. ,   4. ,   1. ,   0. ,   0. ,  95. ],
       [ 11. ,  16. ,   4. ,   3. ,  95. ,   3. , 170. ],
       [ 11. ,  16. ,   4. ,   3. , 150. ,   3. , 170. ],
       [ 13. ,  17. ,   3. ,   2. , 150. ,   3. , 160. ],
       [  6. ,  15. ,   2. ,   1. , 220. ,   2. ,  90. ],
       [  9. ,  15. ,   2. ,   1. , 190. ,   0. ,  40. ],
       [  7. ,  21. ,   3. ,   2. , 220. ,   3. , 130. ],
       [  2. ,  18. ,   3. ,   0. , 170. ,   3. ,  90. ],
       [ 10. ,  13.5,   3. ,   2. , 170. ,   1.5, 120. ],
       [ 14. ,  11. ,   3. ,   1. , 200. ,   6. , 260. ],
       [  3. ,  20. ,   3. ,   0. , 320. ,   1. ,  45. ],
       [  0. ,  13. ,   1. ,   0. ,   0. ,   0. ,  15. ],
       [  0. ,  10. ,   2. ,   0. ,   0. ,   1. ,  50. ],
       [  6. ,  14. ,   4. ,   1. , 135. ,   2. , 110. ],
       [  0. ,  18. ,   5. ,   2. ,   0. ,   2.7, 110. ],
       [ 12. ,  14. ,   3. ,   1. , 210. ,   5. , 240. ],
       [  8. ,  10.5,   3. ,   2. , 140. ,   2.5, 140. ],
       [  6. ,  15. ,   2. ,   0. ,   0. ,   2. , 110. ],
       [  2. ,  23. ,   1. ,   0. , 240. ,   0. ,  30. ],
       [  3. ,  22. ,   2. ,   0. , 290. ,   0. ,  35. ],
       [  0. ,  16. ,   2. ,   0. ,   0. ,   3. ,  95. ],
       [  0. ,  19. ,   3. ,   0. ,   0. ,   4. , 140. ],
       [  0. ,  20. ,   3. ,   0. ,   0. ,   3. , 120. ],
       [ 15. ,   9. ,   2. ,   1. ,  70. ,   1. ,  40. ],
       [  3. ,  16. ,   6. ,   0. , 230. ,   1. ,  55. ],
       [  5. ,  15. ,   2. ,   0. ,  15. ,   3. ,  90. ],
       [  3. ,  21. ,   2. ,   1. , 200. ,   0. ,  35. ],
       [ 14. ,  15. ,   3. ,   1. , 190. ,   4. , 230. ],
       [  3. ,  16. ,   3. ,   1. , 200. ,   3. , 110. ],
       [  3. ,  21. ,   2. ,   1. , 250. ,   0. ,  60. ],
       [ 12. ,  13. ,   1. ,   1. , 140. ,   0. ,  25. ],
       [  3. ,  17. ,   3. ,   1. , 230. ,   3. , 115. ],
       [  3. ,  17. ,   3. ,   1. , 200. ,   3. , 110. ],
       [  8. ,  16. ,   2. ,   1. , 200. ,   1. ,  60. ]])

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=0)

In [14]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression().fit(X_train, y_train)

In [15]:
y_pred = regressor.predict(X_test)

In [20]:
results = pd.DataFrame(y_test, columns= ['test'])
results['predicted'] = y_pred

In [21]:
results

    test   predicted
0    120  113.302739
1    100  101.700738
2    100  103.211016
3     50   56.666868
4    120  105.767878
5    100   96.316470
6     90   88.816987
7    110   93.165035
8    150  149.522540
9    110  113.712864
10   120  117.678372
11    90   92.469466
12    50   49.980223
13   110  113.040502
14   100   99.883621
15   130  133.825173
16   100  101.106989
17   100  105.035401
18    90   93.224680
19   110  109.516811

# Can we do it with SVR?

In [47]:
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler()
X_scaled = X_scaler.fit_transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

y_scaler = StandardScaler()
y_scaled = y_scaler.fit_transform(y_train.reshape((-1, 1)))
y_test_scaled = y_scaler.transform(y_test.reshape((-1, 1)))

regressor = SVR()
regressor.fit(X_scaled, y_scaled.reshape(-1))

/Users/shelbymcgarrah/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/shelbymcgarrah/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/shelbymcgarrah/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

In [48]:
y_pred = regressor.predict(X_test_scaled)

In [50]:
y_pred_unscaled = y_scaler.inverse_transform(y_pred)

In [53]:
svr_results = pd.DataFrame(y_test, columns= ['test'])
svr_results['predicted'] = y_pred_unscaled
svr_results

    test   predicted
0    120  110.510515
1    100  102.361341
2    100  109.739232
3     50   87.210470
4    120  108.948746
5    100   91.538518
6     90   87.104084
7    110   93.480743
8    150  142.409231
9    110  111.884691
10   120  119.364862
11    90   89.431101
12    50   95.353156
13   110  110.984100
14   100   94.776262
15   130  132.673066
16   100  105.125109
17   100  107.333901
18    90   94.594541
19   110  107.424229